"""Shared conf.py helpers for Sphinx projects that link into the Hugo site
and reuse its shared top-nav bar. Used by docs/conf.py (and any future
Sphinx project added under this repo).

Usage in a project's conf.py:

    import sys
    from pathlib import Path

    REPO_ROOT = Path(__file__).parent.parent.resolve()
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import hugo_intersphinx as hi

    intersphinx_mapping = {}
    hi.add_hugo_intersphinx(intersphinx_mapping, REPO_ROOT)
    hi.add_shared_nav_assets(html_static_path, html_css_files, html_js_files, REPO_ROOT)
"""
import os
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    tomllib = None

DEFAULT_HUGO_BASE_URL = "https://eclipse-hephaestus.github.io/hephaestus/"


def hugo_base_url(repo_root: Path) -> str:
    # CI passes the base URL GitHub's configure-pages action resolved for
    # *this* repository (e.g. a fork's own github.io domain) — prefer it so
    # cross-links are correct even if hugo.toml's baseURL wasn't updated.
    env_base = os.environ.get("HUGO_BASE_URL")
    if env_base:
        return env_base if env_base.endswith("/") else env_base + "/"

    hugo_toml = repo_root / "hugo.toml"
    if tomllib is None or not hugo_toml.exists():
        return DEFAULT_HUGO_BASE_URL
    with open(hugo_toml, "rb") as f:
        data = tomllib.load(f)
    base = data.get("baseURL", DEFAULT_HUGO_BASE_URL)
    return base if base.endswith("/") else base + "/"


def add_hugo_intersphinx(intersphinx_mapping: dict, repo_root: Path, key: str = "hugo") -> None:
    """Register the `key:` intersphinx mapping for the Hugo site, using the
    objects.inv generated by scripts/hugo_json_to_objects_inv.py. No-ops
    (with a printed note) if that inventory hasn't been generated yet."""
    inv_path = os.environ.get("HUGO_OBJECTS_INV", str(repo_root / "hugo-objects.inv"))
    if os.path.exists(inv_path):
        intersphinx_mapping[key] = (hugo_base_url(repo_root), inv_path)
    else:
        print(
            f"[conf.py] {inv_path} not found — build Hugo and run "
            f"scripts/hugo_json_to_objects_inv.py first for `{key}:` intersphinx "
            "references to resolve. Continuing without it."
        )


def shared_nav_html_config(repo_root: Path, static_dir: str = "docs/_static") -> dict:
    """HTML config overrides that point at the shared header assets and
    generated nav.json, so every Sphinx project in this repo renders an
    identical header without duplicating files. Merge the returned dict's
    keys into conf.py's own html_static_path/html_css_files/html_js_files/
    html_extra_path."""
    shared_static = repo_root / static_dir
    config = {
        "html_static_path": [str(shared_static)],
        "html_css_files": ["shared-nav.css"],
        "html_js_files": ["shared-nav.js"],
    }

    nav_json = shared_static.parent / "_extra" / "nav.json"
    if nav_json.exists():
        config["html_extra_path"] = [str(nav_json.parent)]
    return config
