# ********************************************************************************
# * Copyright (c) 2026 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************
import os
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    tomllib = None

ROOT = Path(__file__).parent.resolve()
REPO_ROOT = ROOT.parent

project = "Eclipse SDV Hephaestus Requirements"
copyright = "2026, Eclipse Foundation and contributors"
author = "Eclipse SDV Hephaestus"

extensions = [
    "myst_parser",
    "sphinx_needs",
    "sphinx.ext.intersphinx",
]

myst_enable_extensions = ["colon_fence"]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- sphinx-needs ------------------------------------------------------------
needs_types = [
    dict(directive="req", title="Requirement", prefix="REQ_", color="#BFD8D2", style="node"),
    dict(directive="spec", title="Specification", prefix="SPEC_", color="#FEDCD2", style="node"),
    dict(directive="impl", title="Implementation", prefix="IMPL_", color="#DF744A", style="node"),
    dict(directive="test", title="Test Case", prefix="TEST_", color="#DCB239", style="node"),
]
needs_id_required = True
# Exported to <outdir>/needs.json — the sphinx-needs equivalent of objects.inv,
# and the input for needs_external_needs if this ever splits into multiple
# sphinx-needs projects.
needs_build_json = True


# -- intersphinx: link into the Hugo marketing/docs site ---------------------
def _hugo_base_url() -> str:
    default = "https://eclipse-hephaestus.github.io/hephaestus/"

    # CI passes the base URL GitHub's configure-pages action resolved for
    # *this* repository (e.g. a fork's own github.io domain) — prefer it so
    # cross-links are correct even if hugo.toml's baseURL wasn't updated.
    env_base = os.environ.get("HUGO_BASE_URL")
    if env_base:
        return env_base if env_base.endswith("/") else env_base + "/"

    hugo_toml = REPO_ROOT / "hugo.toml"
    if tomllib is None or not hugo_toml.exists():
        return default
    with open(hugo_toml, "rb") as f:
        data = tomllib.load(f)
    base = data.get("baseURL", default)
    return base if base.endswith("/") else base + "/"


# Generated by scripts/hugo_json_to_objects_inv.py from Hugo's public/index.json.
# Must exist before this build runs (see build order in the CI workflow).
_HUGO_OBJECTS_INV = os.environ.get("HUGO_OBJECTS_INV", str(REPO_ROOT / "hugo-objects.inv"))

intersphinx_mapping = {}
if os.path.exists(_HUGO_OBJECTS_INV):
    intersphinx_mapping["hugo"] = (_hugo_base_url(), _HUGO_OBJECTS_INV)
else:
    print(
        f"[conf.py] {_HUGO_OBJECTS_INV} not found — build Hugo and run "
        "scripts/hugo_json_to_objects_inv.py first for `hugo:` intersphinx "
        "references to resolve. Continuing without it."
    )

# -- HTML output --------------------------------------------------------------
html_theme = "furo"
html_static_path = ["_static"]
html_css_files = ["shared-nav.css"]
html_js_files = ["shared-nav.js"]

# nav.json (written alongside hugo-objects.inv by the same conversion script)
# is copied verbatim to the build root so shared-nav.js can fetch it from any
# page depth via DOCUMENTATION_OPTIONS.URL_ROOT.
if (ROOT / "_extra" / "nav.json").exists():
    html_extra_path = ["_extra"]
